[socket]
port = "8080"

[log]
levels = ["INFO", "ERROR", "WARN", "DEBUG", "TRACE"]
enabled = true

[suspend]
classes = ["UserService", "AuthController"]
services = ["PaymentGateway"]
enabled = true

[condition]
classes = ["UserController", "UserService"]
services = ["AuthService", "PaymentGateway"]
enabled = false

[tag.classes]
arslan = ["roleService"]
UserService = ["IGNORE", "DEBUG"]

[tag.services]
AuthService = ["SECURITY", "MONITORING"]
DenemService = ["SECURITY", "MONITORING"]

[tag]
enabled = true

[regexp]
pattern = "(?P<time>\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}[+-]\\d{2}:\\d{2})\\s+(?P<level>\\w+)\\s+(?P<pid>\\d+)\\s+---\\s+\\[(?P<service>[^\\]]+)\\]\\s+\\[(?P<thread>[^\\]]+)\\]\\s+(?P<class>[^:]+)\\s*:\\s*(?P<message>.*)"
sample_log = ""

[pid]
socket_pid = ""
process_pid = ""
