[workspace.package]
name = "log-beacon"
authors = ["Arslan Kucukkafa <arslankucukkafa@gmail.com>"]
version = "0.1.0"
description = "Log Beacon CLI is a tool to view logs from multiple sources"

[workspace]
resolver = "2"
members = ["log-common","log-engine","logctl"]

[workspace.dependencies]
serde = { version = "1.0.217", features = ["derive"] }
log = "0.4.25"